### ISSUE TITLE
What is the license for the code in the repository?

### ISSUE THREAD

**Issue by ronenkat** [vuquangtrong/mkdocs-material-blog#1]
Your readme has an MIT license specified but the LICENSE file is for LGPL3.
Which license reflects the one for the code? it is not clear the way the information is displayed.
Thank you.

**Comment by vuquangtrong** [comment]
Oh I'm sorry for the wrong the license file, I will update the correct license as an MIT one.

**Comment by vuquangtrong** [comment]
I updated the license file ^^
